apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-conference-day-micronaut
spec:
  template:
    metadata:
      name: cloud-conference-day-micronaut-v1
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "20"
    spec:
      containers:
        - image: claudioed/cloud-conference-day-micronaut
          env:
            - name: MESSAGE_DATA
              value: "micronaut"
          ports:
            - name: http1
              containerPort: 8080
              protocol: TCP