apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-conference-day-quarkus
spec:
  template:
    metadata:
      name: cloud-conference-day-quarkus-v1
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: claudioed/cloud-conference-day-quarkus
          env:
            - name: MESSAGE_DATA
              value: "quarkus"
          ports:
            - name: http1
              containerPort: 8080
              protocol: TCP